import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

// Bundles the Page Analyzer content script, including SAM's own card reader (src/domains/ux-designer), into one
// classic script that Chrome loads unpacked. Unminified so the loaded code stays reviewable.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'extension', 'page-analyzer');
// The panel shows the manifest version, so a reload can be confirmed on the page.
const { version } = JSON.parse(readFileSync(path.join(dir, 'manifest.json'), 'utf8'));

// content.js: the app page analysis (isolated world). model-export.js: the model export, which runs in the classic model
// building page's main world to read its Model settings grids through the page's own client.
for (const [entry, outfile] of [['content.ts', 'content.js'], ['model-content.ts', 'model-export.js']]) {
  await build({
    entryPoints: [path.join(dir, 'src', entry)],
    outfile: path.join(dir, 'dist', outfile),
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['chrome111'],
    charset: 'utf8',
    legalComments: 'none',
    logLevel: 'warning',
    define: { __EXTENSION_VERSION__: JSON.stringify(version) },
    banner: { js: `// Anaplan Analyzer ${version}. Generated by scripts/build-page-analyzer.mjs from extension/page-analyzer/src; do not edit.` },
  });
  console.log(`Built extension/page-analyzer/dist/${outfile}`);
}
